# Generated by Django 4.2.30 on 2026-09-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_wishlist_wishlistitem_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('seller', 'slug'), name='unique_seller_product_slug'),
        ),
    ]
