# Generated by Django 4.2.30 on 2026-09-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('seller', 'Seller'), ('security', 'Security'), ('system', 'System'), ('marketplace', 'Marketplace')], max_length=20),
        ),
    ]
