"""Abstract base for payment provider integrations."""

from abc import ABC, abstractmethod


class PaymentProvider(ABC):
    """Base class that all payment providers must implement."""

    @abstractmethod
    def initialize_transaction(self, amount, email, reference, callback_url=None, metadata=None):
        """Initialize a payment transaction with the provider.

        Args:
            amount: Amount in the currency's subunit (e.g. kobo for NGN).
            email: Customer email address.
            reference: Unique payment reference generated by NUVORA.
            callback_url: Optional URL the provider redirects to after payment.
            metadata: Optional dict of internal metadata to attach.

        Returns:
            dict with at least:
                authorization_url: URL to redirect the customer to.
                access_code: Provider access/authorization code.
                reference: The provider's reference (may differ from ours).

        Raises:
            PaymentInitializationError: If the provider API call fails.
        """
        ...

    @abstractmethod
    def verify_transaction(self, reference):
        """Verify a transaction by reference with the provider.

        Args:
            reference: The payment reference to verify.

        Returns:
            dict with normalized fields:
                status: 'success', 'failed', 'abandoned', 'pending', etc.
                provider_transaction_id: The provider's transaction ID.
                reference: The provider's reference.
                amount: Amount in subunits as returned by the provider.
                currency: Currency code as returned by the provider.

        Raises:
            PaymentVerificationError: If the verification call fails.
        """
        ...

    @abstractmethod
    def verify_webhook_signature(self, raw_body, signature):
        """Verify that a webhook signature is authentic.

        Args:
            raw_body: The raw bytes of the request body.
            signature: The signature string from the provider's header.

        Returns:
            True if the signature is valid, False otherwise.
        """
        ...


class PaymentInitializationError(Exception):
    """Raised when a provider fails to initialize a transaction."""


class PaymentVerificationError(Exception):
    """Raised when a provider fails to verify a transaction."""
