# Generated by Django 4.2.30 on 2026-09-19 04:41

import apps.payments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack')], max_length=20)),
                ('payment_reference', models.CharField(default=apps.payments.models.generate_payment_reference, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('provider_transaction_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'), models.Index(fields=['payment_reference'], name='payments_pa_payment_87c4c1_idx'), models.Index(fields=['provider_transaction_id'], name='payments_pa_provide_edad36_idx')],
            },
        ),
    ]
